"""add_wallet_transactions_table

Revision ID: 99d4fb3530ef
Revises: b2c3d4e5f6a7
Create Date: 2026-04-23 00:16:53.490948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99d4fb3530ef'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gateway', sa.String(length=50), nullable=True),
    sa.Column('gateway_ref_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__wallet_transactions__user_id__users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__wallet_transactions'))
    )
    op.create_index('idx_wallet_reference', 'wallet_transactions', ['reference_type', 'reference_id'], unique=False)
    op.create_index('idx_wallet_status', 'wallet_transactions', ['status'], unique=False)
    op.create_index('idx_wallet_type', 'wallet_transactions', ['type'], unique=False)
    op.create_index('idx_wallet_user', 'wallet_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix__wallet_transactions__user_id'), 'wallet_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__wallet_transactions__user_id'), table_name='wallet_transactions')
    op.drop_index('idx_wallet_user', table_name='wallet_transactions')
    op.drop_index('idx_wallet_type', table_name='wallet_transactions')
    op.drop_index('idx_wallet_status', table_name='wallet_transactions')
    op.drop_index('idx_wallet_reference', table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    # ### end Alembic commands ###
