"""fix back_populates problem and cascading

Revision ID: 3fbc6c36d1d2
Revises: 5bdf24128a6d
Create Date: 2026-03-24 16:10:36.618279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fbc6c36d1d2'
down_revision: Union[str, None] = '5bdf24128a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
