"""remove email field

Revision ID: 5bdf24128a6d
Revises: 57b9ad2a28ba
Create Date: 2026-03-24 14:35:06.797227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bdf24128a6d'
down_revision: Union[str, None] = '57b9ad2a28ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'email_enabled')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=11),
               nullable=False)
    op.drop_index(op.f('ix__users__email'), table_name='users')
    op.create_index(op.f('ix__users__phone'), 'users', ['phone'], unique=True)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix__users__phone'), table_name='users')
    op.create_index(op.f('ix__users__email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=20),
               nullable=True)
    op.add_column('notification_preferences', sa.Column('email_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
