"""a lot of change

Revision ID: ca45d86f9f2f
Revises: a1b2c3d4e5f6
Create Date: 2026-04-06 13:46:06.570272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca45d86f9f2f'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forbidden_keywords',
    sa.Column('keyword', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_regex', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__forbidden_keywords'))
    )
    op.create_index('idx_forbidden_keywords_active', 'forbidden_keywords', ['is_active'], unique=False)
    op.create_index('idx_forbidden_keywords_category', 'forbidden_keywords', ['category'], unique=False)
    op.create_index(op.f('ix__forbidden_keywords__keyword'), 'forbidden_keywords', ['keyword'], unique=False)
    # Performance indexes for sync_states (high-frequency queries)
    op.create_index('idx_sync_states_last_sync', 'sync_states', ['last_sync_timestamp'], unique=False)
    op.create_index('idx_sync_states_status', 'sync_states', ['status'], unique=False)
    op.create_table('forbidden_product_rules',
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__forbidden_product_rules'))
    )
    op.create_index('idx_forbidden_rules_active', 'forbidden_product_rules', ['is_active'], unique=False)
    op.create_index('idx_forbidden_rules_type', 'forbidden_product_rules', ['rule_type'], unique=False)
    op.create_table('sync_states',
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sync_mode', sa.String(length=20), nullable=True),
    sa.Column('last_sync_timestamp', sa.DateTime(), nullable=True),
    sa.Column('cursor_token', sa.String(length=500), nullable=True),
    sa.Column('total_synced', sa.Integer(), nullable=True),
    sa.Column('created_count', sa.Integer(), nullable=True),
    sa.Column('updated_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['shop_integrations.id'], name=op.f('fk__sync_states__integration_id__shop_integrations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__sync_states')),
    sa.UniqueConstraint('integration_id', 'entity_type', name='uq_sync_state_integration_entity')
    )
    op.alter_column('audit_logs', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'reason',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_table('sync_states')
    op.drop_index('idx_forbidden_rules_type', table_name='forbidden_product_rules')
    op.drop_index('idx_forbidden_rules_active', table_name='forbidden_product_rules')
    op.drop_table('forbidden_product_rules')
    op.drop_index(op.f('ix__forbidden_keywords__keyword'), table_name='forbidden_keywords')
    op.drop_index('idx_forbidden_keywords_category', table_name='forbidden_keywords')
    op.drop_index('idx_forbidden_keywords_active', table_name='forbidden_keywords')
    op.drop_table('forbidden_keywords')
    # ### end Alembic commands ###
