"""some changes for webhook functionality

Revision ID: f800cd7fcfd7
Revises: 3fbc6c36d1d2
Create Date: 2026-03-31 10:13:49.452626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f800cd7fcfd7'
down_revision: Union[str, None] = '3fbc6c36d1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outgoing_webhook_logs',
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['shop_integrations.id'], name=op.f('fk__outgoing_webhook_logs__integration_id__shop_integrations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__outgoing_webhook_logs'))
    )
    op.create_index('idx_outgoing_webhook_logs_integration', 'outgoing_webhook_logs', ['integration_id'], unique=False)
    op.create_index('idx_outgoing_webhook_logs_retry', 'outgoing_webhook_logs', ['next_retry_at'], unique=False)
    op.create_index('idx_outgoing_webhook_logs_status', 'outgoing_webhook_logs', ['status'], unique=False)
    op.create_table('outgoing_webhook_dlq',
    sa.Column('outgoing_webhook_log_id', sa.UUID(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['outgoing_webhook_log_id'], ['outgoing_webhook_logs.id'], name=op.f('fk__outgoing_webhook_dlq__outgoing_webhook_log_id__outgoing_webhook_logs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__outgoing_webhook_dlq'))
    )
    op.create_index('idx_outgoing_webhook_dlq_status', 'outgoing_webhook_dlq', ['status'], unique=False)
    op.add_column('platforms', sa.Column('webhook_allowed_ips', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('platforms', sa.Column('webhook_rate_limit', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('platforms', sa.Column('webhook_timestamp_tolerance', sa.Integer(), nullable=True))
    op.add_column('shop_integrations', sa.Column('webhook_secret_encrypted', sa.String(length=512), nullable=True))
    op.add_column('shop_integrations', sa.Column('webhook_status', sa.String(length=30), nullable=True))
    op.add_column('shop_integrations', sa.Column('webhook_registered_at', sa.DateTime(), nullable=True))
    op.add_column('shop_integrations', sa.Column('webhook_previous_secret_encrypted', sa.String(length=512), nullable=True))
    op.add_column('shop_integrations', sa.Column('webhook_secret_rotated_at', sa.DateTime(), nullable=True))
    op.add_column('shop_integrations', sa.Column('webhook_previous_secret_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_integrations', 'webhook_previous_secret_expires_at')
    op.drop_column('shop_integrations', 'webhook_secret_rotated_at')
    op.drop_column('shop_integrations', 'webhook_previous_secret_encrypted')
    op.drop_column('shop_integrations', 'webhook_registered_at')
    op.drop_column('shop_integrations', 'webhook_status')
    op.drop_column('shop_integrations', 'webhook_secret_encrypted')
    op.drop_column('platforms', 'webhook_timestamp_tolerance')
    op.drop_column('platforms', 'webhook_rate_limit')
    op.drop_column('platforms', 'webhook_allowed_ips')
    op.drop_index('idx_outgoing_webhook_dlq_status', table_name='outgoing_webhook_dlq')
    op.drop_table('outgoing_webhook_dlq')
    op.drop_index('idx_outgoing_webhook_logs_status', table_name='outgoing_webhook_logs')
    op.drop_index('idx_outgoing_webhook_logs_retry', table_name='outgoing_webhook_logs')
    op.drop_index('idx_outgoing_webhook_logs_integration', table_name='outgoing_webhook_logs')
    op.drop_table('outgoing_webhook_logs')
    # ### end Alembic commands ###
